version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    container_name: nginx
    networks:
      - laravel

  php:
    build: .docker/php
    volumes:
      - .:/var/www
    container_name: php
    links:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    container_name: mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
